Import Libraries

In [1]:
import pandas as pd
import sqlite3

Load the Cleaned Dataset

In [2]:
df = pd.read_csv("SuperMarket_Analysis_Cleaned.csv")

Create an SQLite Database

In [3]:
# Create SQLite database in memory
conn = sqlite3.connect(":memory:")

Convert the DataFrame into an SQL Table

In [4]:
df.to_sql(
    "SuperMarket_Data",
    conn,
    if_exists="replace",
    index=False
)

1000

View the Table

In [5]:
query = """
SELECT *
FROM SuperMarket_Data
LIMIT 5;
"""

pd.read_sql(query, conn)

,Transaction_ID,Branch,City,Customer_Type,Gender,Product_Line,Unit_Price,Quantity,Tax,Revenue,Date,Time,Payment,Expense,gross margin percentage,Profit,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

Revenue by Month (Line Chart Data)

In [8]:
query = """
SELECT
    strftime('%Y-%m', Date) AS Month,
    ROUND(SUM(Revenue), 2) AS Total_Revenue
FROM SuperMarket_Data
GROUP BY Month
ORDER BY Month;
"""

monthly_revenue = pd.read_sql(query, conn)

monthly_revenue

     Month  Total_Revenue
0  2019-01      116291.87
1  2019-02       97219.37
2  2019-03      109455.51

In [7]:
query = """
SELECT *
FROM SuperMarket_Data
LIMIT 1;
"""

pd.read_sql(query, conn)

,Transaction_ID,Branch,City,Customer_Type,Gender,Product_Line,Unit_Price,Quantity,Tax,Revenue,Date,Time,Payment,Expense,gross margin percentage,Profit,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1

Total Expenses by Product Line

In [9]:
query = """
SELECT
    Product_Line,
    ROUND(SUM(Expense), 2) AS Total_Expense
FROM SuperMarket_Data
GROUP BY Product_Line
ORDER BY Total_Expense DESC;
"""

expense_product = pd.read_sql(query, conn)

expense_product

             Product_Line  Total_Expense
0      Food and beverages       53471.28
1       Sports and travel       52497.93
2  Electronic accessories       51750.03
3     Fashion accessories       51719.90
4      Home and lifestyle       51297.06
5       Health and beauty       46851.18

Total Profit by City

In [10]:
query = """
SELECT
    City,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM SuperMarket_Data
GROUP BY City
ORDER BY Total_Profit DESC;
"""

profit_city = pd.read_sql(query, conn)

profit_city

        City  Total_Profit
0  Naypyitaw       5265.18
1     Yangon       5057.16
2   Mandalay       5057.03

Revenue by Branch

In [11]:
query = """
SELECT
    Branch,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM SuperMarket_Data
GROUP BY Branch
ORDER BY Total_Revenue DESC;
"""

branch_revenue = pd.read_sql(query, conn)

branch_revenue

  Branch  Total_Revenue
0   Giza      110568.71
1   Alex      106200.37
2  Cairo      106197.67

Revenue by Payment Method

In [12]:
query = """
SELECT
    Payment,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM SuperMarket_Data
GROUP BY Payment
ORDER BY Total_Revenue DESC;
"""

payment_revenue = pd.read_sql(query, conn)

payment_revenue

       Payment  Total_Revenue
0         Cash      112206.57
1      Ewallet      109993.11
2  Credit card      100767.07

Revenue by Product Line

In [13]:
query = """
SELECT
    Product_Line,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM SuperMarket_Data
GROUP BY Product_Line
ORDER BY Total_Revenue DESC;
"""

product_revenue = pd.read_sql(query, conn)

product_revenue

             Product_Line  Total_Revenue
0      Food and beverages       56144.84
1       Sports and travel       55122.83
2  Electronic accessories       54337.53
3     Fashion accessories       54305.90
4      Home and lifestyle       53861.91
5       Health and beauty       49193.74

Revenue by Customer Type

In [14]:
query = """
SELECT
    Customer_Type,
    ROUND(SUM(Revenue),2) AS Total_Revenue
FROM SuperMarket_Data
GROUP BY Customer_Type;
"""

customer_revenue = pd.read_sql(query, conn)

customer_revenue

  Customer_Type  Total_Revenue
0        Member      189694.76
1        Normal      133271.99

Average Customer Rating

In [15]:
query = """
SELECT
    Product_Line,
    ROUND(AVG(Rating),2) AS Average_Rating
FROM SuperMarket_Data
GROUP BY Product_Line
ORDER BY Average_Rating DESC;
"""

rating = pd.read_sql(query, conn)

rating

             Product_Line  Average_Rating
0      Food and beverages            7.11
1     Fashion accessories            7.03
2       Health and beauty            7.00
3       Sports and travel            6.92
4  Electronic accessories            6.92
5      Home and lifestyle            6.84

Overall Profit Margin

In [16]:
query = """
SELECT
    ROUND(
        (SUM(Profit) * 100.0) / SUM(Revenue),
        2
    ) AS Profit_Margin_Percentage
FROM SuperMarket_Data;
"""

profit_margin = pd.read_sql(query, conn)

profit_margin

   Profit_Margin_Percentage
0                      4.76

Executive KPI Query

In [17]:
query = """
SELECT

COUNT(*) AS Total_Transactions,

ROUND(SUM(Revenue),2) AS Total_Revenue,

ROUND(SUM(Expense),2) AS Total_Expense,

ROUND(SUM(Profit),2) AS Total_Profit,

ROUND(AVG(Revenue),2) AS Average_Order_Value,

ROUND(AVG(Rating),2) AS Average_Rating

FROM SuperMarket_Data;
"""

kpis = pd.read_sql(query, conn)

kpis

,Total_Transactions,Total_Revenue,Total_Expense,Total_Profit,Average_Order_Value,Average_Rating
0,1000,322966.75,307587.38,15379.37,322.97,6.97